Buttons added
adityabisoi/startup-incubator pull request #56
Opened 2022-03-26 14:59 UTC by ayush25102001

#32
![Screenshot (14)](https://user-images.githubusercontent.com/78008646/160245172-776e206e-e53b-4a8b-a192-2469702835a3.png)

2022-04-02 05:39 UTC, ayush25102001 commented
Please review @rohan-kulkarni-25

2022-04-05 03:42 UTC, ayush25102001 commented
@pranav2012 please review

2022-04-05 09:43 UTC, ayush25102001 commented
PR for issue #32

2022-04-05 12:19 UTC, pranav2012 commented on .gitignore
> +package-lock.json
don't add package-lock in .gitignore

2022-04-05 12:20 UTC, pranav2012 commented on client/.gitignore
> +package-lock.json
don't add package-lock in .gitignore

2022-04-05 12:21 UTC, pranav2012 requested changes
you have removed mui and used bootstrap instead
use mui for adding the buttons

2022-04-05 12:24 UTC, ayush25102001 commented
> you have removed mui and used bootstrap instead
> use mui for adding the buttons

Ok sir!!

2022-04-08 12:12 UTC, pranav2012 commented
> > you have removed mui and used bootstrap instead
> > use mui for adding the buttons
> 
> Ok sir!!

any updates @ayush25102001 ?

2022-04-08 12:20 UTC, ayush25102001 commented
> > > you have removed mui and used bootstrap instead
> > > use mui for adding the buttons
> > 
> > 
> > Ok sir!!
> 
> any updates @ayush25102001 ?

I don’t know mui I am trying

2022-04-11 22:29 UTC, adityabisoi commented
@ayush25102001 Please resolve the conflicts.

2022-04-12 03:31 UTC, ayush25102001 commented
> @ayush25102001 Please resolve the conflicts.

done !!

2022-04-13 15:20 UTC, merged